import oracledb, time

conn = oracledb.connect(user="sankhya", password="mqh41r", dsn="192.168.1.55/ORCL")
cur = conn.cursor()

print("--- Testando consulta consolidada rápida para Setembro/2026 ---")
t0 = time.time()

sql = """
WITH
base_com AS (
    SELECT
        CAB.CODEMP,
        COALESCE(CAB.CODCENCUS,0) AS CODCENCUS,
        CAB.CODNAT AS CODNAT,
        'VALORNF' AS REF,
        SUM(((ITE.VLRTOT - ITE.VLRDESC - ITE.VLRREPRED + ITE.VLRSUBST + ITE.VLRIPI) * VCA.INDITENSBRUTO)) AS VALOR
    FROM TGFCAB CAB, TGFITE ITE, TGFTOP TOP, VGFCAB VCA
    WHERE CAB.CODTIPOPER = TOP.CODTIPOPER
      AND CAB.DHTIPOPER = TOP.DHALTER
      AND CAB.NUNOTA = ITE.NUNOTA
      AND CAB.TIPMOV IN ('V', 'D')
      AND CAB.STATUSNOTA = 'L' 
      AND CAB.NUNOTA = VCA.NUNOTA
      AND (TOP.GOLSINAL = -1 OR BONIFICACAO='S' OR CAB.CODTIPOPER IN (3218,3327))
      AND (NOT EXISTS(SELECT 1 FROM TGFVAR VAR WHERE VAR.NUNOTA = ITE.NUNOTA AND VAR.NUNOTAORIG = VAR.NUNOTA AND VAR.SEQUENCIAORIG = ITE.SEQUENCIA))
      AND (TOP.ATUALFINTERC <> 'N' OR TOP.ATUALESTTERC = 'N' OR ITE.TERCEIROS <> 'S')
      AND ITE.SEQUENCIA > 0    
      AND TOP.GOLDEV IN (1,-1) 
      AND CAB.DTENTSAI >= TO_DATE('2026-09-01','YYYY-MM-DD')
      AND CAB.DTENTSAI <  TO_DATE('2026-10-01','YYYY-MM-DD')
    GROUP BY CAB.CODEMP, CAB.CODCENCUS, CAB.CODNAT
    
    UNION ALL
    
    SELECT
        CAB.CODEMP,
        COALESCE(CAB.CODCENCUS,0) AS CODCENCUS,
        CAB.CODNAT AS CODNAT,
        'CUSTOGER' AS REF,
        SUM(CASE WHEN CAB.CODTIPOPER IN (4092,3320,4091) THEN (ITE.AD_CUSTO_OPER_CHINA* ITE.QTDNEG)*CAB.VLRMOEDA ELSE
            COALESCE(CASE WHEN (CAB.CODEMP <> 501 OR TOP.CODTIPOPER=3291) THEN (F_OBTEM_CUSTO_MQ ((CASE WHEN TOP.CODTIPOPER=3291 THEN 2 ELSE CAB.CODEMP END), ITE.CODPROD, CAB.DTNEG, CAB.DTNEG) * ITE.QTDNEG) END * (CASE WHEN CAB.CODTIPOPER=11000 THEN 0 ELSE 1 END), 0)
        END) AS VALOR
    FROM TGFCAB CAB, TGFITE ITE, TGFTOP TOP, VGFCAB VCA
    WHERE CAB.CODTIPOPER = TOP.CODTIPOPER
      AND CAB.DHTIPOPER = TOP.DHALTER
      AND CAB.NUNOTA = ITE.NUNOTA
      AND CAB.TIPMOV IN ('V', 'D')
      AND CAB.STATUSNOTA = 'L' 
      AND CAB.NUNOTA = VCA.NUNOTA
      AND (TOP.GOLSINAL = -1 OR BONIFICACAO='S' OR CAB.CODTIPOPER IN (3218,3327))
      AND (NOT EXISTS(SELECT 1 FROM TGFVAR VAR WHERE VAR.NUNOTA = ITE.NUNOTA AND VAR.NUNOTAORIG = VAR.NUNOTA AND VAR.SEQUENCIAORIG = ITE.SEQUENCIA))
      AND (TOP.ATUALFINTERC <> 'N' OR TOP.ATUALESTTERC = 'N' OR ITE.TERCEIROS <> 'S')
      AND ITE.SEQUENCIA > 0    
      AND TOP.GOLDEV IN (1,-1) 
      AND CAB.DTENTSAI >= TO_DATE('2026-09-01','YYYY-MM-DD')
      AND CAB.DTENTSAI <  TO_DATE('2026-10-01','YYYY-MM-DD')
    GROUP BY CAB.CODEMP, CAB.CODCENCUS, CAB.CODNAT
    
    UNION ALL
    
    SELECT
        CAB.CODEMP,
        COALESCE(CAB.CODCENCUS,0) AS CODCENCUS,
        CAB.CODNAT AS CODNAT,
        'CUSSIMICM' AS REF,
        SUM(CASE WHEN CAB.CODEMP <> 501 THEN (OBTEMCUSTO(ITE.CODPROD,'S',CAB.CODEMP,'N',0,'N',0,CAB.DTENTSAI,3) * ITE.QTDNEG) END * (CASE WHEN CAB.CODTIPOPER=11000 THEN 0 ELSE 1 END)) AS VALOR
    FROM TGFCAB CAB, TGFITE ITE, TGFTOP TOP, VGFCAB VCA
    WHERE CAB.CODTIPOPER = TOP.CODTIPOPER
      AND CAB.DHTIPOPER = TOP.DHALTER
      AND CAB.NUNOTA = ITE.NUNOTA
      AND CAB.TIPMOV IN ('V', 'D')
      AND CAB.STATUSNOTA = 'L' 
      AND CAB.NUNOTA = VCA.NUNOTA
      AND (TOP.GOLSINAL = -1 OR BONIFICACAO='S' OR CAB.CODTIPOPER IN (3218,3327))
      AND (NOT EXISTS(SELECT 1 FROM TGFVAR VAR WHERE VAR.NUNOTA = ITE.NUNOTA AND VAR.NUNOTAORIG = VAR.NUNOTA AND VAR.SEQUENCIAORIG = ITE.SEQUENCIA))
      AND (TOP.ATUALFINTERC <> 'N' OR TOP.ATUALESTTERC = 'N' OR ITE.TERCEIROS <> 'S')
      AND ITE.SEQUENCIA > 0    
      AND TOP.GOLDEV IN (1,-1) 
      AND CAB.DTENTSAI >= TO_DATE('2026-09-01','YYYY-MM-DD')
      AND CAB.DTENTSAI <  TO_DATE('2026-10-01','YYYY-MM-DD')
    GROUP BY CAB.CODEMP, CAB.CODCENCUS, CAB.CODNAT
    
    UNION ALL
    
    SELECT
        CAB.CODEMP,
        COALESCE(CAB.CODCENCUS,0) AS CODCENCUS,
        CAB.CODNAT AS CODNAT,
        'IMPOSTO' AS REF,
        SUM(F_OBTEM_IMPOSTOSITE(CAB.NUNOTA, ITE.SEQUENCIA)) AS VALOR
    FROM TGFCAB CAB, TGFITE ITE, TGFTOP TOP, VGFCAB VCA
    WHERE CAB.CODTIPOPER = TOP.CODTIPOPER
      AND CAB.DHTIPOPER = TOP.DHALTER
      AND CAB.NUNOTA = ITE.NUNOTA
      AND CAB.TIPMOV IN ('V', 'D')
      AND CAB.STATUSNOTA = 'L' 
      AND CAB.NUNOTA = VCA.NUNOTA
      AND (TOP.GOLSINAL = -1 OR BONIFICACAO='S' OR CAB.CODTIPOPER IN (3218,3327))
      AND (NOT EXISTS(SELECT 1 FROM TGFVAR VAR WHERE VAR.NUNOTA = ITE.NUNOTA AND VAR.NUNOTAORIG = VAR.NUNOTA AND VAR.SEQUENCIAORIG = ITE.SEQUENCIA))
      AND (TOP.ATUALFINTERC <> 'N' OR TOP.ATUALESTTERC = 'N' OR ITE.TERCEIROS <> 'S')
      AND ITE.SEQUENCIA > 0    
      AND TOP.GOLDEV IN (1,-1) 
      AND CAB.DTENTSAI >= TO_DATE('2026-09-01','YYYY-MM-DD')
      AND CAB.DTENTSAI <  TO_DATE('2026-10-01','YYYY-MM-DD')
    GROUP BY CAB.CODEMP, CAB.CODCENCUS, CAB.CODNAT
),
base_fin AS (
    SELECT 
        FIN.CODEMP,
        FIN.CODCENCUS,
        FIN.CODNAT,
        'VALORFIN' AS REF,
        SUM(FIN.VLRDESDOB * FIN.RECDESP) AS VALOR
    FROM VGFFINRAT FIN 
    WHERE FIN.RECDESP IN (1,-1)
      AND FIN.PROVISAO = 'N'
      AND (
          (FIN.CODNAT NOT IN (2010101,2010116,2010120,12010201,12010401,12020408) 
           AND FIN.DTNEG >= TO_DATE('2026-09-01','YYYY-MM-DD') AND FIN.DTNEG < TO_DATE('2026-10-01','YYYY-MM-DD'))
          OR
          (FIN.CODNAT IN (2010101,2010116,2010120,12010201,12010401,12020408)
           AND FIN.DTNEG >= TO_DATE('2026-10-01','YYYY-MM-DD') AND FIN.DTNEG < TO_DATE('2026-11-01','YYYY-MM-DD'))
      )
    GROUP BY FIN.CODEMP, FIN.CODCENCUS, FIN.CODNAT
),
base_inc AS (
    SELECT 
        CODEMP, CODCENCUS, CODNAT, 'INCQLIK' AS REF,
        SUM(CASE WHEN TIPOITEM <> 'ORC' THEN VALOR ELSE 0 END) AS VALOR
    FROM AD_FLUXODRE
    WHERE DTNEG >= TO_DATE('2026-09-01','YYYY-MM-DD') AND DTNEG < TO_DATE('2026-10-01','YYYY-MM-DD')
    GROUP BY CODEMP, CODCENCUS, CODNAT
),
base_orc AS (
    SELECT 
        501 AS CODEMP, CODCENCUS, CODNAT, REF,
        SUM(VLRORC) AS ORCAMENTO
    FROM AD_ORCAMENTO
    WHERE DTREF >= TO_DATE('2026-09-01','YYYY-MM-DD') AND DTREF < TO_DATE('2026-10-01','YYYY-MM-DD')
      AND CODCENCUS NOT IN (21010000)
    GROUP BY CODCENCUS, CODNAT, REF
),
tudo AS (
    SELECT CODEMP, CODCENCUS, CODNAT, REF, VALOR, 0 AS ORCAMENTO FROM base_com
    UNION ALL
    SELECT CODEMP, CODCENCUS, CODNAT, REF, VALOR, 0 AS ORCAMENTO FROM base_fin
    UNION ALL
    SELECT CODEMP, CODCENCUS, CODNAT, REF, VALOR, 0 AS ORCAMENTO FROM base_inc
    UNION ALL
    SELECT CODEMP, CODCENCUS, CODNAT, REF, 0 AS VALOR, ORCAMENTO FROM base_orc
)
SELECT 
    c.BLOCO,
    c.TITULO,
    SUM(t.VALOR     * NVL(c.FATOR, 1)) AS REALIZADO,
    SUM(t.ORCAMENTO * NVL(c.FATOR, 1)) AS ORCADO
FROM tudo t
JOIN VMQ_CADDRE c ON c.CODCENCUS = t.CODCENCUS
                 AND c.CODNAT    = t.CODNAT
                 AND c.REF = (
                     CASE WHEN t.CODNAT IN (12010301, 12010302) AND t.REF = 'VALORNF' 
                          THEN 'CUSTOGER' 
                          ELSE t.REF 
                     END
                 )
GROUP BY c.BLOCO, c.TITULO
ORDER BY c.BLOCO, c.TITULO
"""

cur.execute(sql)
rows = cur.fetchall()
t_total = time.time() - t0
print(f"Sucesso! {len(rows)} linhas em {t_total:.2f}s:")
for r in rows:
    print(f"  {r[0]} | {r[1]} -> Realizado: {r[2]} | Orçado: {r[3]}")

cur.close()
conn.close()
